# Generated by Django 3.2.7 on 2022-05-31 17:27

from django.db import migrations, models
import menu.models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="Image",
            field=models.ImageField(default="", upload_to=menu.models.upload_to),
        ),
    ]
