# Generated by Django 3.2.7 on 2022-06-01 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0004_alter_order_zip_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="email",
            new_name="user",
        ),
    ]
