# Generated by Django 3.2.7 on 2022-06-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0006_remove_order_order_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.EmailField(max_length=60, verbose_name="email"),
        ),
    ]
