saycow = input(">")
print(" " + "_" * len(saycow))
print("< " + saycow + " >")
print(" " + "-" * len(saycow))
print("        \   ^__^")
print("         \  (oo)\_______")
print("            (__)\       )\/\\")
print("                ||----w |")
print("                ||     ||")