// The full project catalog — every folder under projects/.
// catalog.json is generated by scripts/gen-catalog.mjs (`npm run catalog`).

import type { CatalogProject } from "@/types";
import { REPO_URL } from "@/lib/data";
import catalog from "./catalog.json";

export const CATALOG: CatalogProject[] = catalog as CatalogProject[];

export const RUNNABLE = CATALOG.filter((p) => p.runnable);

export function getCatalogProject(id: string): CatalogProject | undefined {
  return CATALOG.find((p) => p.id === id);
}

/** GitHub URL of a project's source folder in the repo. */
export function catalogFolderUrl(p: CatalogProject): string {
  const path = p.folder
    .split("/")
    .map((seg) => encodeURIComponent(seg))
    .join("/");
  return `${REPO_URL}/tree/main/projects/${path}`;
}
