# Importing the 'random' module to generate random numbers
import random

# Function for the user to guess the number generated by the computer
def guess():
    '''
    This function generates a random number between 1 and 20 (inclusive)
    and allows the user to guess the number. It continues to prompt
    the user for input until the correct number is guessed.
    """
    '''
    # Generate a random number between 1 and 20 (inclusive)
    n = random.randrange(1, 20)

    # This loop continues until the user guesses the correct number.
    while True:
        user_input = input("Enter your number: ")
        try:
            varGuess = int(user_input)
            if n == varGuess:
                print(f"Congratulations!! You guessed the number {n} correctly")
                break
            elif varGuess < n:
                print("OOPS! Guess something higher!")
            elif varGuess > n:
                print("OOPS! Guess something lower!")
        except ValueError:
            # Handle invalid input (not an integer)
            print("Invalid input. Please enter a valid integer.")




# Function for the computer to guess the number chosen by the user
def computer_guess():
    global CompGuess

    # Request user input to get the number to be guessed by the computer
    x = int(input("Enter your number: "))

    # Initialize the lower and upper bounds for the computer's guessing range
    low = 1
    high = x

    # Variable to store the user's feedback on the computer's guesses
    CompAns = ""

    # Continue the loop until the computer guesses the correct number
    while CompAns != "c":
        if low != high:
            # Generate a random guess within the current range
            CompGuess = random.randint(low, high)
        else:
            CompGuess = (
                low  # If the range is reduced to a single value, guess that number
            )

        # Ask the user if the computer's guess is too high, too low, or correct
        CompAns = input(
            f"Is {CompGuess} too high (h), too low (l), or correct (c)? \n=>"
        ).lower()

        # Adjust the guessing range based on the user's feedback
        if CompAns == "h":  # If the computer's guess is too high
            high = CompGuess - 1
        elif CompAns == "l":  # If the computer's guess is too low
            low = CompGuess + 1

    # Display a message when the computer guesses the correct number
    print(f"Yay! The computer guessed your number, {CompGuess}, correctly!")


if __name__ == "__main__":
    # Display options to select the gaming mode
    print(
        "Select gaming mode\n Press 1 to guess the number\nPress 2 to choose the number"
    )
    Gmode = int(input())

    # Call the appropriate function based on the selected gaming mode
    if Gmode == 1:
        guess()
    if Gmode == 2:
        computer_guess()
