# Importing the 'random' module to generate random numbers
import random
COMP_GUESS = None


# Function for the user to guess the number generated by the computer
def guess():
    """
    This function generates a random number between 1 and 20 (inclusive)
    and allows the user to guess the number. It continues to prompt
    the user for input until the correct number is guessed.

    Returns:
    None
    """
    # Generate a random number between 1 and 20 (inclusive)
    n = random.randrange(1, 20)

    # This loop continues until the user guesses the correct number.
    while True:
        user_input = input("Enter your number: ")
        try:
            var_guess = int(user_input)
            if n == var_guess:
                print(f"Congratulations!! You guessed the number {n} correctly")
                return
            elif var_guess < n:
                print("OOPS! Guess something higher!")
            elif var_guess > n:
                print("OOPS! Guess something lower!")
        except ValueError:
            # Handle invalid input (not an integer)
            print("Invalid input. Please enter a valid integer.")


# Function for the computer to guess the number chosen by the user
def computer_guess():
    """
    Play the guessing game where the computer tries to guess the user's number.

    This function prompts the user to enter a number, and then the computer will make guesses
    and adjust the guessing range based on the user's feedback until it correctly guesses the number.

    Returns:
    None
    """
    global COMP_GUESS
    # Variable to store the user's feedback on the computer's guesses
    comp_ans = ""

    # Get the number to be guessed by the computer, validating the input
    while True:
        try:
            # Request user input to get the number to be guessed by the computer
            x = int(input("Enter your number: "))
            break
        except ValueError:
            print("Invalid input. Please enter a valid integer.")

    # Initialize the lower and upper bounds for the computer's guessing range
    low = 1
    high = x

    # Continue the loop until the computer guesses the correct number
    while comp_ans != "c":
        if low != high:
            # Generate a random guess within the current range
            COMP_GUESS = random.randint(low, high)
        else:
            COMP_GUESS = (
                low  # If the range is reduced to a single value, guess that number
            )

        # Ask the user if the computer's guess is too high, too low, or correct
        comp_ans = input(
            f"Is {COMP_GUESS} too high (h), too low (l), or correct (c)? \n=>"
        ).lower()
        # Ask the user if the computer's guess is too high, too low, or correct
        while comp_ans not in ["h", "l", "c"]:
            comp_ans = input(
                f"Is {COMP_GUESS} too high (h), too low (l), or correct (c)? \n=>"
            ).lower()
            if comp_ans not in ["h", "l", "c"]:
                print("Invalid input. Please enter 'h', 'l', or 'c'.")

        # Adjust the guessing range based on the user's feedback
        if comp_ans == "h":  # If the computer's guess is too high
            high = COMP_GUESS - 1
        elif comp_ans == "l":  # If the computer's guess is too low
            low = COMP_GUESS + 1

    # Display a message when the computer guesses the correct number
    print(f"Yay! The computer guessed your number, {COMP_GUESS}, correctly!")


def main():
    """
        Main function to initiate the number guessing game.

        This function allows the user to select the gaming mode and start either the number guessing
        game or the computer guessing game based on the user's choice.

        Returns:
        None
        """
    while True:
        # Display options to select the gaming mode
        user_input = input("Select gaming mode\nPress 1 to guess the number\nPress 2 to choose the number\n")

        if user_input in ["1", "2"]:
            game_mode = int(user_input)
            break
        else:
            print("Invalid choice. Please enter either 1 or 2.")

    if game_mode == 1:
        guess()
    elif game_mode == 2:
        computer_guess()


if __name__ == "__main__":
    main()
