// Shared types for the pyBegin frontend.

export type CategoryId = "all" | "games" | "tools" | "web" | "fun";

export interface Project {
  id: string;
  name: string;
  cat: Exclude<CategoryId, "all">;
  blurb: string;
  lines: number;
  deps: string;
  emoji: string;
  /** GitHub handle of the contributor who first added this project. */
  author: string;
  /** Folder path under projects/ in the repo (for the source link). */
  repoPath: string;
  /** Can run fully in-browser via Pyodide (pure-stdlib console programs). */
  playground?: boolean;
}

export interface Category {
  id: CategoryId;
  name: string;
  count: number;
}

/**
 * One entry in the full project catalog (every folder under projects/).
 * Generated by scripts/gen-catalog.mjs into src/lib/catalog.json.
 */
export interface CatalogProject {
  /** URL slug — unique across the catalog. */
  id: string;
  /** Folder path under projects/ in the repo. */
  folder: string;
  /** Display name (from the project's README title). */
  name: string;
  /** One-line description (from the README). */
  blurb: string;
  emoji: string;
  /** Can run in the in-browser Pyodide playground. */
  runnable: boolean;
  /** A playground source file exists for this project. */
  hasPlayground: boolean;
  /** Line count of the project's main .py file. */
  lines: number;
  /** GitHub handle of the contributor who first added this project. */
  author?: string;
}

export interface Contributor {
  handle: string;
  name: string;
  commits: number;
  role?: string;
}

/** One entry in the full contributor list (scraped from the README). */
export interface RepoContributor {
  handle: string;
  name: string;
  avatar: string;
}

export interface Stats {
  projects: number;
  contributors: number;
  stars: number;
  forks: number;
}

export interface LearningPath {
  id: string;
  name: string;
  tag: string;
  desc: string;
  items: string[];
  hue: number;
}
