print("Welcome to MAD LIB!! ")
adjective1=input("Enter an adjective ")
noun1=input("Enter a noun ")
place1=input("Enter a name of a place ")
piece_of_clothing1=input("Enter a piece of clothing ")
adjective2=input("Enter an adjective ")
adjective3=input("Enter an adjective ")
adjective4=input("Enter an adjective ")
song_title1=input("Enter a song title ")
food1=input("Enter a food item ")
adjective5=input("Enter an adjective ")
past_tense_verb1=input("Enter a past tense verb ")
noun2=input("Enter a noun ")
past_tense_verb2=input("Enter a past tense verb ")
past_tense_verb3=input("Enter a past tense verb ")
noun3=input("Enter a noun ")
noun4=input("Enter a noun ")
verb1=input("Enter a verb ")
verb2=input("Enter a verb ")
verb3=input("Enter a verb ")
adjective6=input("Enter an adjetctive ")

print("It was a "+adjective1+' Summer day. '+noun1+' and I were excited to go camping at '+place1+'. It was my first time going there. I packed my favorite '+piece_of_clothing1+'. It is '+adjective2+' and '+adjective3+'. Perfect for camping! On the road we went in our '+adjective4+' van! We were listening to '+song_title1+' all the way down. The drive was about 5 hours but it was so worth it. When we got there we unpacked the van. I could smell '+food1+' being cooked. It smelled '+adjective5+'. I '+past_tense_verb1+' to the room I was staying in with my '+noun1+'. The next thing I knew, '+noun2+' came and '+past_tense_verb2+' on the bed. I heard my mom scream,"Get off the bed!" I '+past_tense_verb3+' outside. I saw '+noun3+'. It was '+noun4+'. Over the next few days i got to '+verb1+', '+verb2+', and '+verb3+'. My camping trip was '+adjective6+'.')